eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8016/eureka/
server:
  port: 8012
spring:
  application:
    name: service-feign
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: true
feign:
  hystrix:
    enabled: true
