eureka:
  client:
    service-url:
      defaultZone: http://localhost:8016/eureka/
spring:
  application:
    name: client
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      percentage: 1
server:
  port: 8009
