spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ralapchi/springcloudconfig
          search-paths: demo
      label: master
server:
  port: 8014
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/



